services:
  db:
    image: postgres:15.3
    environment:
      POSTGRES_DB: todo_list
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: